apiVersion: v1
kind: Service
metadata:
  name: datanode1
spec:
  ports:
    - name: khaman
      port: 22
      targetPort: 22
    - name: a
      port: 8020
      targetPort: 8020
    - name: b
      port: 8042
      targetPort: 8042
    - name: c
      port: 8088
      targetPort: 8088
    - name: d
      port: 9000
      targetPort: 9000
    - name: e
      port: 10020
      targetPort: 10020
    - name: f
      port: 19888
      targetPort: 19888
    - name: g
      port: 50010
      targetPort: 50010
    - name: h
      port: 50020
      targetPort: 50020
    - name: i
      port: 50070
      targetPort: 50070
    - name: j
      port: 50075
      targetPort: 50075
    - name: k
      port: 50090
      targetPort: 50090
  selector:
    target: datanode
