apiVersion: v1
kind: Service
metadata:
  name: worker0
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: worker0
  #type: LoadBalancer


---
#new subworker
apiVersion: v1
kind: Service
metadata:
  name: subworker0
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: worker0
  #type: LoadBalancer

---
#master code
apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: controller
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: master
  type: LoadBalancer

