kind: PersistentVolume
apiVersion: v1
metadata:
  name: core-nfs
  labels:
    type: nfs
spec:
  storageClassName: nfs-core
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    #server: nfs-server-core.default.svc.cluster.local
    #path: "/"
    server: 192.168.0.12
    path: "/mnt/core"
    readOnly: false
    
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shadow-nfs
  labels:
    type: nfs
spec:
  storageClassName: nfs-shadow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    #server: nfs-server-shadow.default.svc.cluster.local
    #path: "/"
    server: 192.168.0.12
    path: "/mnt/shadow"
    readOnly: false

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-local
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/dev/disk/"
  
