apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server-core
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-core
  template:
    metadata:
      labels:
        role: nfs-server-core
    spec:
      containers:
      - name: nfs-server-core
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /disk
            name: mypvc
      volumes:
        - name: mypvc
          gcePersistentDisk:
            pdName: core-storage
            fsType: ext4
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server-shadow
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server-shadow
  template:
    metadata:
      labels:
        role: nfs-server-shadow
    spec:
      containers:
      - name: nfs-server-shadow
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /disk
            name: shadowpvc
      volumes:
        - name: shadowpvc
          gcePersistentDisk:
            pdName: shadow-disk
            fsType: ext4
