apiVersion: v1
kind: Service
metadata:
  name: worker0
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: worker0
  #type: LoadBalancer

---
#new worker
apiVersion: v1
kind: Service
metadata:
  name: worker1
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: worker1
  #type: LoadBalancer

---
#new worker
apiVersion: v1
kind: Service
metadata:
  name: subworker00
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: subworker00
  #type: LoadBalancer

---
#new subworker
apiVersion: v1
kind: Service
metadata:
  name: subworker01
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: subworker01
  #type: LoadBalancer

---
#new subworker
apiVersion: v1
kind: Service
metadata:
  name: subworker02
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: subworker02
  #type: LoadBalancer

---
#new subworker
apiVersion: v1
kind: Service
metadata:
  name: subworker03
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: subworker03
  #type: LoadBalancer

---
#new subworker
apiVersion: v1
kind: Service
metadata:
  name: subworker10
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: subworker10
  #type: LoadBalancer

---
#new subworker
apiVersion: v1
kind: Service
metadata:
  name: subworker11
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: subworker11
  #type: LoadBalancer

---
#new subworker
apiVersion: v1
kind: Service
metadata:
  name: subworker12
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: subworker12
  #type: LoadBalancer

---
#new subworker
apiVersion: v1
kind: Service
metadata:
  name: subworker13
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: subworker13
  #type: LoadBalancer

---
#new subworker
#master code
apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: controller
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: files
    port: 22
    targetPort: 22
  - name: rsync
    port: 873
    targetPort: 873
  selector:
    target: master
  type: LoadBalancer

