apiVersion: v1
kind: Pod
metadata:
  name: worker0
  labels:
    app: server
    target: worker0
spec:
      selector:
        matchLabels:
          target: worker0
      volumes:
        # - name: nfs-store
        #   persistentVolumeClaim:
        #     claimName: nfsclaim
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydra
          volumeMounts:
            # - name: nfs-store 
            #   mountPath: /dev/nfs/store
            - name: local-store
              mountPath: /dev/local/store
          image: worker
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Pod
metadata:
  name: worker1
  labels:
    app: server
    target: worker1
spec:
      selector:
        matchLabels:
          target: worker1
      volumes:
        # - name: nfs-store
        #   persistentVolumeClaim:
        #     claimName: nfsclaim
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydra
          volumeMounts:
            # - name: nfs-store 
            #   mountPath: /dev/nfs/store
            - name: local-store
              mountPath: /dev/local/store
          image: worker
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: server
    target: master
spec:
      selector:
        matchLabels:
          target: master
      volumes:
        # - name: nfs-store
        #   persistentVolumeClaim:
        #     claimName: nfsclaim
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydra
          volumeMounts:
            # - name: nfs-store 
            #   mountPath: /dev/nfs/store
            - name: local-store
              mountPath: /dev/local/store
          image: unixmaster
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
