apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker0
  labels:
    app: server
    target: worker0
spec:
  selector:
    matchLabels:
      target: worker0
  replicas: 1
  template:
    metadata:
      labels:
        target: worker0
    spec:
      volumes:
        - name: nfs-store
          persistentVolumeClaim:
            claimName: nfs-core-claim
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydraa
          volumeMounts:
            - name: nfs-store 
              mountPath: /dev/core/
            - name: local-store
              mountPath: /dev/pers/
          image: altariax0x01/km_bunny_worker
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
            - containerPort: 5000
            - containerPort: 22
            - containerPort: 873
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
#new worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subworker00
  labels:
    app: server
    target: subworker00
spec:
  selector:
    matchLabels:
      target: subworker00
  replicas: 1
  template:
    metadata:
      labels:
        target: subworker00
    spec:
      volumes:
        - name: nfs-store
          persistentVolumeClaim:
            claimName: nfs-core-claim
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydraa
          volumeMounts:
            - name: nfs-store 
              mountPath: /dev/core/
            - name: local-store
              mountPath: /dev/pers/
          image: altariax0x01/km_bunny_subworker
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
            - containerPort: 5000
            - containerPort: 22
            - containerPort: 873
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
#new subworker

#master code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app: server
    target: controller
spec:
  selector:
    matchLabels:
      target: controller
  replicas: 1
  template:
    metadata:
      labels:
        target: controller
    spec:
      volumes:
        - name: nfs-core
          persistentVolumeClaim:
            claimName: nfs-core-claim
        - name: nfs-shadow
          persistentVolumeClaim:
            claimName: nfs-shadow-claim
            
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydrax
          volumeMounts:
            - name: nfs-core
              mountPath: /dev/core/
            - name: nfs-shadow
              mountPath: /mnt/shadow/
            - name: local-store
              mountPath: /dev/pers/
          image: altariax0x01/km_bunny_controller
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
            - containerPort: 5000
            - containerPort: 22
            - containerPort: 873
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: server
    target: master
spec:
  selector:
    matchLabels:
      target: master
  replicas: 1
  template:
    metadata:
      labels:
        target: master
    spec:
      volumes:
        - name: nfs-core
          persistentVolumeClaim:
            claimName: nfs-core-claim
        - name: nfs-shadow
          persistentVolumeClaim:
            claimName: nfs-shadow-claim
            
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydrax
          volumeMounts:
            - name: nfs-core
              mountPath: /dev/core/
            - name: nfs-shadow
              mountPath: /mnt/shadow/
            - name: local-store
              mountPath: /dev/pers/
          image: altariax0x01/km_bunny_master
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
            - containerPort: 5000
            - containerPort: 22
            - containerPort: 873
      dnsPolicy: ClusterFirst
      restartPolicy: Always
