---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rabbit-svr
spec:
  template:
    metadata:
      labels:
        app: rabbit-svr
    spec:
      containers:
      - name: rabbit
        image: altariax0x01/rabbitmq   ##CLOUD
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-svr
  labels:
    app: rabbit-svr
spec:
  ports:
  - name: client
    port: 5672
    protocol: TCP
    targetPort: 5672
    
  selector:
    app: rabbit-svr

