apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
      
      containers:
        - name: hydra
          image: worker
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
