---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka2-port
    protocol: TCP
  - port: 9091
    name: kafka1-port
    protocol: TCP
  - port: 9090
    name: kafka-port
    protocol: TCP
  - port: 9093
    name: kafka3-port
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer
