apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker0
  labels:
    app: server
    target: worker0
spec:
  selector:
    matchLabels:
      target: worker0
  replicas: 1
  template:
    metadata:
      labels:
        target: worker0
    spec:
      volumes:
        # - name: nfs-store
        #   persistentVolumeClaim:
        #     claimName: nfsclaim
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydraa
          volumeMounts:
            # - name: nfs-store 
            #   mountPath: /dev/nfs/store
            - name: local-store
              mountPath: /dev/local/store
          image: altariax0x01/worker
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker1
  labels:
    app: server
    target: worker1
spec:
  selector:
    matchLabels:
      target: worker1
  replicas: 1
  template:
    metadata:
      labels:
        target: worker1
    spec:
      volumes:
        # - name: nfs-store
        #   persistentVolumeClaim:
        #     claimName: nfsclaim
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydrab
          volumeMounts:
            # - name: nfs-store 
            #   mountPath: /dev/nfs/store
            - name: local-store
              mountPath: /dev/local/store
          image: altariax0x01/worker
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: server
    target: master
spec:
  selector:
    matchLabels:
      target: master
  replicas: 1
  template:
    metadata:
      labels:
        target: master
    spec:
      volumes:
        # - name: nfs-store
        #   persistentVolumeClaim:
        #     claimName: nfsclaim
        - name: local-store
          persistentVolumeClaim:
            claimName: localclaim
      containers:
        - name: hydrax
          volumeMounts:
            # - name: nfs-store 
            #   mountPath: /dev/nfs/store
            - name: local-store
              mountPath: /dev/local/store
          image: altariax0x01/unixmaster
          imagePullPolicy: Always
          env:
            - name: GET_HOSTS_FROM
              value: dns
          command: ["sh","start.sh"]
          ports:
            - containerPort: 4000
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
