# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: pv-nfs
#   labels:
#     type: nfs
# spec:
#   storageClassName: nfs
#   capacity:
#     storage: 6Gi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     server: nfs-server.default.svc.cluster.local
#     path: "/"
#     readOnly: false

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-local
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/dev/disk/"
  
