kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-core-claim
spec:
  storageClassName: nfs-core
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-shadow-claim
spec:
  storageClassName: nfs-shadow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
      
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: localclaim
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
