apiVersion: v1
kind: Pod
metadata:
    name: datapod
    labels:
        target: datapod
spec:
    nodeSelector:
        mode: hdfs
    containers:
      - name: hydragon
        image: harisekhon/hadoop
        imagePullPolicy: IfNotPresent
        env:
            - name: GET_HOSTS_FROM
              value: dns
        #command: ["sh","start.sh"]
        ports:
            - containerPort: 8020
            - containerPort: 22
            - containerPort: 8042
            - containerPort: 8088
            - containerPort: 9000
            - containerPort: 10020
            - containerPort: 19888
            - containerPort: 50010
            - containerPort: 50020
            - containerPort: 50070
            - containerPort: 50075
            - containerPort: 50090
    dnsPolicy: ClusterFirst
    restartPolicy: Always
