kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsclaim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: localclaim
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
