apiVersion: v1
kind: Service
metadata:
  name: worker0
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: svc-port1
    port: 873
    targetPort: 873
  - name: svc-port2
    port: 22
    targetPort: 22

  selector:
    target: worker0
  type: LoadBalancer

---
#new worker
apiVersion: v1
kind: Service
metadata:
  name: worker1
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: svc-port1
    port: 873
    targetPort: 873
  - name: svc-port2
    port: 22
    targetPort: 22

  selector:
    target: worker1
  type: LoadBalancer

---
#new worker
apiVersion: v1
kind: Service
metadata:
  name: worker2
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: svc-port1
    port: 873
    targetPort: 873
  - name: svc-port2
    port: 22
    targetPort: 22

  selector:
    target: worker2
  type: LoadBalancer

---
#new worker
#master code
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  ports:
  - name: normal
    port: 4000
    targetPort: 4000
  - name: lr
    port: 5000
    targetPort: 5000
  - name: svc-port1
    port: 873
    targetPort: 22
  - name: svc-port2
    port: 22
    targetPort: 22
  selector:
    target: master
  type: LoadBalancer



